### ISSUE TITLE
项目中潜在的一些bug

### ISSUE THREAD

**Issue by Yuziquan** [monimm/LLandLR#1]
bug1、对于某些文法，求非终结符的FIRST集，空指针出错
ans：断点调试后发现，是因为在执行getFollow函数时，调用的getFirst(right);，是求串的FIRST集，在getFirst函数中，直接调用了firstSet.get(tn);，但是tn的FIRST集有可能没有事先求出，所以在前面加上 if(!firstSet.containsKey(tn)    {      getFirst(tn);  } 即可

bug2、对于某些比较复杂一点的文法，还是会存在“求出的FOLLOW集不完整”的现象，比如如下文法：
S->I|o
I->i(E)SL
L->eS|ε
E->a|b

代码改动如下：
public String [] inputExperssion = { "S->I", "S->o", "I->i(E)SL", "L->eS", "L->~", "E->a", "E->b"};

 public String strInput = "i(a)i(b)oeo$";
public Character S = 'S';
analyzeStatck.push('S');

按照您的代码，求出的FOLLOW集情况如下：
Follow S: $ e
Follow E: )
Follow I: $
Follow L: $

但是，我们知道，正确的是这样：
Follow S: $ e
Follow E: )
Follow I: $ e
Follow L: $ e

也就是说会发生不完整的现象。

ans：本人目前也不知如何解决，希望楼主看看~~

**Comment by monimm** [comment]
新的代码已修复，原因是求follow集前没有递归处理。
你的例子分析成功。

**Comment by Yuziquan** [comment]
thanks！

**Comment by monimm** [comment]
我看了你的编译器项目，挺不错的，加油。
之前获取follow集合的代码逻辑不清楚，命名也不规范，重构后如果还有问题再一起解决。

**Comment by Yuziquan** [comment]
哈哈，谢谢夸赞！

**Comment by Yuziquan** [comment]
楼主修改的很认真！赞！
